In [2]:
# import module
import pandas as pd
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [ ]:
#How to convert the index of a series into a column of a dataframe?
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)

ser1 = pd.Series(mylist)
ser2 = pd.Series(myarr)
ser3 = pd.Series(mydict)

ser1, ser2, ser3

In [5]:
#. How to convert the index of a series into a column of a dataframe?
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)

df = ser.to_frame().reset_index()
df.head()

index  0
0     a  0
1     b  1
2     c  2
3     d  4
4     e  3

In [9]:
#  How to combine many series to form a dataframe?
import numpy as np
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))

df = pd.concat([ser1,ser2],axis = 1)
df = pd.DataFrame({'col1':ser1,'col2':ser2})
df.head()

col1  col2
0    a     0
1    b     1
2    c     2
3    e     3
4    d     4

In [10]:
#How to assign name to the series’ index?
ser = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))

ser.name = 'alphabets'
ser.head()

0    a
1    b
2    c
3    e
4    d
Name: alphabets, dtype: object

In [11]:
#How to get the items of series A not present in series B?
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

ser1 = ser1[~ser1.isin(ser2)]
ser1.head()

0    1
1    2
2    3
dtype: int64

In [14]:
#How to get the items not common to both series A and series B
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

ser_u = pd.Series(np.union1d(ser1,ser2))
ser_i = pd.Series(np.intersect1d(ser1,ser2))

ser_u
ser_i
ser = ser_u[~ser_u.isin(ser_i)]
ser

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
dtype: int64

0    4
1    5
dtype: int64

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64

In [16]:
#How to get the minimum, 25th percentile, median, 75th, and max of a numeric series?
ser = pd.Series(np.random.normal(10, 5, 25))

np.percentile(ser,  q=[0, 25, 50, 75, 100])
ser.describe()

array([  0.92235183,   7.67403593,  11.89722737,  14.29781947,  17.67167709])

count    25.000000
mean     11.042421
std       4.737327
min       0.922352
25%       7.674036
50%      11.897227
75%      14.297819
max      17.671677
dtype: float64

In [23]:
#How to get frequency counts of unique items of a series?
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))

ser_unique = pd.Series(ser.unique()).count()

ser.value_counts()

d    7
a    5
e    5
g    4
f    3
b    3
c    2
h    1
dtype: int64

In [29]:
# How to keep only top 2 most frequent values as it is and replace everything else as ‘Other’?
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))

ser.value_counts().index[:2]
ser.value_counts()
ser[~ser.isin(ser.value_counts().index[:2])] = 'Other'
ser

Int64Index([3, 2], dtype='int64')

3    4
2    4
4    3
1    1
dtype: int64

0     Other
1     Other
2         3
3         2
4         2
5     Other
6         3
7         3
8         2
9         3
10        2
11    Other
dtype: object

In [31]:
#How to bin a numeric series to 10 groups of equal size?
ser = pd.Series(np.random.random(20))

pd.qcut(ser, q = [0, .10, .20, .3, .4, .5, .6, .7, .8, .9, 1], 
        labels=['1st', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th', '9th', '10th']).head()

0    10th
1     5th
2     1st
3     4th
4     2nd
dtype: category
Categories (10, object): [1st < 2nd < 3rd < 4th ... 7th < 8th < 9th < 10th]

In [34]:
#How to convert a numpy array to a dataframe of given shape? (L1)
ser = pd.Series(np.random.randint(1, 10, 35))

type(ser.values.reshape(7,5))
df = pd.DataFrame(ser.values.reshape(7,5))
df

numpy.ndarray

0  1  2  3  4
0  4  8  3  3  5
1  6  9  7  1  3
2  9  9  5  2  8
3  4  4  5  5  2
4  2  1  7  2  5
5  8  3  1  1  4
6  8  1  7  1  7

In [38]:
#How to find the positions of numbers that are multiples of 3 from a series?
ser = pd.Series(np.random.randint(1, 10, 7))

ser
np.argwhere(ser % 3 == 0)

0    4
1    2
2    9
3    1
4    3
5    4
6    4
dtype: int32

array([[2],
       [4]], dtype=int64)

In [39]:
#How to extract items at given positions from a series
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]

ser.take(pos)

0     a
4     e
8     i
14    o
20    u
dtype: object

In [42]:
# How to stack two series vertically and horizontally ?
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))

pd.concat([ser1,ser2] , axis = 1)
pd.concat([ser1,ser2],axis = 0)
#or 
ser1.append(ser2)

0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e

0    0
1    1
2    2
3    3
4    4
0    a
1    b
2    c
3    d
4    e
dtype: object

0    0
1    1
2    2
3    3
4    4
0    a
1    b
2    c
3    d
4    e
dtype: object

In [3]:
#How to get the positions of items of series A in another series B?
ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])

[np.where(i ==ser1)[0].tolist()[0] for i in ser2]
#or
[pd.Index(ser1).get_loc(i) for i in ser2]

[5, 4, 0, 8]

[5, 4, 0, 8]

In [4]:
#How to compute the mean squared error on a truth and predicted series?
truth = pd.Series(range(10))
pred = pd.Series(range(10)) + np.random.random(10)

np.mean((truth - pred)**2)

0.4106221686503428

In [7]:
# How to convert the first character of each element in a series to uppercase?
ser = pd.Series(['how', 'to', 'kick', 'ass?'])

pd.Series([i.title() for i in ser])
#or 
ser.map(lambda x : x.title())
#lambda argument: manipulate(argument) 

0     How
1      To
2    Kick
3    Ass?
dtype: object

0     How
1      To
2    Kick
3    Ass?
dtype: object

In [10]:
#How to calculate the number of characters in each word in a series?
ser = pd.Series(['how', 'to', 'kick', 'ass?'])

pd.Series([len(i) for i in ser])
ser.map(lambda i : len(i))

0    3
1    2
2    4
3    4
dtype: int64

0    3
1    2
2    4
3    4
dtype: int64

In [12]:
# How to compute difference of differences between consequtive numbers of a series?
ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])

ser.diff().tolist()
ser.diff().diff().tolist()


[nan, 2.0, 3.0, 4.0, 5.0, 6.0, 6.0, 8.0]

[nan, nan, 1.0, 1.0, 1.0, 1.0, 0.0, 2.0]

In [13]:
#How to convert a series of date-strings to a timeseries?
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

pd.to_datetime(ser)

0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]

In [17]:
#How to get the day of month, week number, day of year and day of week from a series of date strings?
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

#solution 
from dateutil.parser import parse
ser_ts = ser.map(lambda x: parse(x))
#year
print(ser_ts.dt.day.tolist())
ser_ts.dt.weekofyear.tolist()
ser_ts.dt.dayofyear.tolist()
ser_ts.dt.weekday_name.tolist()

[1, 2, 3, 4, 5, 6]


[53, 5, 9, 14, 19, 23]

[1, 33, 63, 94, 125, 157]

['Friday', 'Wednesday', 'Saturday', 'Thursday', 'Monday', 'Saturday']

In [18]:
#How to convert year-month string to dates corresponding to the 4th day of the month?
ser = pd.Series(['Jan 2010', 'Feb 2011', 'Mar 2012'])

#solution 1 
from dateutil.parser import parse
ser_dt = ser.map(lambda i : parse(i))

ser_datestr = ser_dt.dt.year.astype('str') + '-' + ser_dt.dt.month.astype('str') + '-' + '04'
ser_datestr


0    2010-1-04
1    2011-2-04
2    2012-3-04
dtype: object

In [21]:
#How to filter words that contain atleast 2 vowels from a series?
ser = pd.Series(['Apple', 'Orange', 'Plan', 'Python', 'Money'])

vowel = ['a','e','i','u','o']

from collections import Counter
mask = ser.map(lambda x : sum([Counter(x.lower()).get(i,0) for i in list('aeiou')]) >= 2)
ser[mask]



0     Apple
1    Orange
4     Money
dtype: object

In [27]:
#How to filter valid emails from a series?
emails = pd.Series(['buying books at amazom.com', 'rameses@egypt.com', 'matt@t.co', 'narendra@modi.com'])
pattern ='[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'

import re

mask = emails.map(lambda x: bool(re.match(pattern, x)))
emails[mask]

emails.str.findall(pattern, flags = re.IGNORECASE)



1    rameses@egypt.com
2            matt@t.co
3    narendra@modi.com
dtype: object

0                     []
1    [rameses@egypt.com]
2            [matt@t.co]
3    [narendra@modi.com]
dtype: object

In [37]:
#How to get the mean of a series grouped by another series?
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))
print(weights.tolist())
print(fruit.tolist())

pd_data = pd.concat([fruit,weights],axis = 1)
pd_data.groupby(0).mean()
#or 

weights.groupby(fruit).mean()

[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
['banana', 'carrot', 'banana', 'banana', 'banana', 'banana', 'banana', 'apple', 'banana', 'apple']


1
0          
apple   9.0
banana  5.0
carrot  2.0

apple     9.0
banana    5.0
carrot    2.0
dtype: float64

In [42]:
#How to compute the euclidean distance between two series?
p = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
q = pd.Series([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])

sum((p-q)**2)**0.5

#or
np.linalg.norm(p-q)

18.165902124584949

18.165902124584949

In [45]:
#How to find all the local maxima (or peaks) in a numeric series?
ser = pd.Series([2, 10, 3, 4, 9, 10, 2, 7, 3])

dd = np.diff(np.sign(np.diff(ser)))
peak_locs = np.where(dd == -2)[0] +1
peak_locs


array([1, 5, 7], dtype=int64)

In [54]:
#How to replace missing spaces in a string with the least frequent character?
my_str = 'dbc deb abed gade'

from collections import Counter
ser = pd.Series(list(my_str))

freq = ser.value_counts()
freq
least_freq = freq.dropna().index[-1]
least_freq
''.join(ser.replace(' ',least_freq))



d    4
     3
b    3
e    3
a    2
c    1
g    1
dtype: int64

'g'

'dbcgdebgabedggade'

In [56]:
#How to create a TimeSeries starting ‘2000-01-01’ and 10 weekends (saturdays) after that having random numbers as values?
ser = pd.Series(np.random.randint(1,10,10), pd.date_range('2000-01-01', periods=10,freq = 'W-SAT'))
ser

2000-01-01    2
2000-01-08    8
2000-01-15    5
2000-01-22    7
2000-01-29    9
2000-02-05    1
2000-02-12    2
2000-02-19    5
2000-02-26    2
2000-03-04    3
Freq: W-SAT, dtype: int32

In [61]:
#How to fill an intermittent time series so all missing dates show up with values of previous non-missing date?
ser = pd.Series([1,10,3,np.nan], index=pd.to_datetime(['2000-01-01', '2000-01-03', '2000-01-06', '2000-01-08']))
ser
ser.resample('D').ffill() 
# alternatives
ser.resample('D').bfill()  #fill with next value
ser.resample('D').bfill().ffill()    #fill next else prev value


2000-01-01     1.0
2000-01-03    10.0
2000-01-06     3.0
2000-01-08     NaN
dtype: float64

2000-01-01     1.0
2000-01-02     1.0
2000-01-03    10.0
2000-01-04    10.0
2000-01-05    10.0
2000-01-06     3.0
2000-01-07     3.0
2000-01-08     NaN
Freq: D, dtype: float64

2000-01-01     1.0
2000-01-02    10.0
2000-01-03    10.0
2000-01-04     3.0
2000-01-05     3.0
2000-01-06     3.0
2000-01-07     NaN
2000-01-08     NaN
Freq: D, dtype: float64

2000-01-01     1.0
2000-01-02    10.0
2000-01-03    10.0
2000-01-04     3.0
2000-01-05     3.0
2000-01-06     3.0
2000-01-07     3.0
2000-01-08     3.0
Freq: D, dtype: float64

In [68]:
#How to compute the autocorrelations of a numeric series?
ser = pd.Series(np.arange(20) + np.random.normal(1, 10, 20))

autocorrelations = [ser.autocorr(i).round(2) for i in range(11)]
autocorrelations[1:]
np.argmax(np.abs(autocorrelations[1:])) + 1

[1.0,
 -0.16,
 0.48999999999999999,
 0.0,
 0.089999999999999997,
 0.14999999999999999,
 -0.17000000000000001,
 0.42999999999999999,
 -0.029999999999999999,
 0.22,
 0.029999999999999999]

[-0.16,
 0.48999999999999999,
 0.0,
 0.089999999999999997,
 0.14999999999999999,
 -0.17000000000000001,
 0.42999999999999999,
 -0.029999999999999999,
 0.22,
 0.029999999999999999]

2

In [76]:
#How to import only every nth row from a csv file to create a dataframe
df= pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', chunksize=50)

df2 = pd.DataFrame()

for chunk in df:
    df2 = df2.append(chunk.iloc[0,:])
    
df2

URLError: <urlopen error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。>

In [77]:
#How to change column values when importing csv to a dataframe?

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', 
                 converters={'medv': lambda x: 'High' if float(x) > 25 else 'Low'})

df


URLError: <urlopen error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。>

In [86]:
# How to create a dataframe with rows as strides from a given series?
L = pd.Series(range(15))

def gen_strides(a, stride_len = 5, window_len = 5):
    n_strides = ((a.size - window_len)//stride_len) + 1
    return np.array([a[s:(s+window_len)] for s in np.arange(0, a.size, stride_len)[:n_strides]])
gen_strides(L, stride_len=2, window_len=4)



array([[ 0,  1,  2,  3],
       [ 2,  3,  4,  5],
       [ 4,  5,  6,  7],
       [ 6,  7,  8,  9],
       [ 8,  9, 10, 11],
       [10, 11, 12, 13]])

In [87]:
# How to import only specified columns from a csv file?
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', usecols=['crim', 'medv'])
print(df.head())

      crim  medv
0  0.00632  24.0
1  0.02731  21.6
2  0.02729  34.7
3  0.03237  33.4
4  0.06905  36.2


In [88]:
#How to get the nrows, ncolumns, datatype, summary stats of each column of a dataframe? Also get the array and list equivalent
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

df.shape

df.dtypes

df.get_dtype_counts()

df.dtypes.value_counts()

df.describe()

df.values

df.values.tolist()

(93, 27)

Manufacturer           object
Model                  object
Type                   object
Min.Price             float64
Price                 float64
Max.Price             float64
MPG.city              float64
MPG.highway           float64
AirBags                object
DriveTrain             object
Cylinders              object
EngineSize            float64
Horsepower            float64
RPM                   float64
Rev.per.mile          float64
Man.trans.avail        object
Fuel.tank.capacity    float64
Passengers            float64
Length                float64
Wheelbase             float64
Width                 float64
Turn.circle           float64
Rear.seat.room        float64
Luggage.room          float64
Weight                float64
Origin                 object
Make                   object
dtype: object

float64    18
object      9
dtype: int64

float64    18
object      9
dtype: int64

Min.Price      Price  Max.Price   MPG.city  MPG.highway  EngineSize  \
count  86.000000  91.000000  88.000000  84.000000    91.000000   91.000000   
mean   17.118605  19.616484  21.459091  22.404762    29.065934    2.658242   
std     8.828290   9.724280  10.696563   5.841520     5.370293    1.045845   
min     6.700000   7.400000   7.900000  15.000000    20.000000    1.000000   
25%    10.825000  12.350000  14.575000  18.000000    26.000000    1.800000   
50%    14.600000  17.700000  19.150000  21.000000    28.000000    2.300000   
75%    20.250000  23.500000  24.825000  25.000000    31.000000    3.250000   
max    45.400000  61.900000  80.000000  46.000000    50.000000    5.700000   

       Horsepower          RPM  Rev.per.mile  Fuel.tank.capacity  Passengers  \
count   86.000000    90.000000     87.000000           85.000000   91.000000   
mean   144.000000  5276.666667   2355.000000           16.683529    5.076923   
std     53.455204   605.554811    486.916616            3.375748    1.045953   
min     55.000000  3800.000000   1320.000000            9.200000    2.000000   
25%    100.750000  4800.000000   2017.500000           14.500000    4.000000   
50%    140.000000  5200.000000   2360.000000           16.500000    5.000000   
75%    170.000000  5787.500000   2565.000000           19.000000    6.000000   
max    300.000000  6500.000000   3755.000000           27.000000    8.000000   

           Length   Wheelbase      Width  Turn.circle  Rear.seat.room  \
count   89.000000   92.000000  87.000000    88.000000       89.000000   
mean   182.865169  103.956522  69.448276    38.954545       27.853933   
std     14.792651    6.856317   3.778023     3.304157        3.018129   
min    141.000000   90.000000  60.000000    32.000000       19.000000   
25%    174.000000   98.000000  67.000000    36.000000       26.000000   
50%    181.000000  103.000000  69.000000    39.000000       27.500000   
75%    192.000000  110.000000  72.000000    42.000000       30.000000   
max    219.000000  119.000000  78.000000    45.000000       36.000000   

       Luggage.room       Weight  
count     74.000000    86.000000  
mean      13.986486  3104.593023  
std        3.120824   600.129993  
min        6.000000  1695.000000  
25%       12.000000  2647.500000  
50%       14.000000  3085.000000  
75%       16.000000  3567.500000  
max       22.000000  4105.000000

array([['Acura', 'Integra', 'Small', ..., 2705.0, 'non-USA',
        'Acura Integra'],
       [nan, 'Legend', 'Midsize', ..., 3560.0, 'non-USA', 'Acura Legend'],
       ['Audi', '90', 'Compact', ..., 3375.0, 'non-USA', 'Audi 90'],
       ..., 
       ['Volkswagen', 'Corrado', 'Sporty', ..., 2810.0, 'non-USA',
        'Volkswagen Corrado'],
       ['Volvo', '240', 'Compact', ..., 2985.0, 'non-USA', 'Volvo 240'],
       [nan, '850', 'Midsize', ..., 3245.0, 'non-USA', 'Volvo 850']], dtype=object)

[['Acura',
  'Integra',
  'Small',
  12.9,
  15.9,
  18.8,
  25.0,
  31.0,
  'None',
  'Front',
  '4',
  1.8,
  140.0,
  6300.0,
  2890.0,
  'Yes',
  13.2,
  5.0,
  177.0,
  102.0,
  68.0,
  37.0,
  26.5,
  nan,
  2705.0,
  'non-USA',
  'Acura Integra'],
 [nan,
  'Legend',
  'Midsize',
  29.2,
  33.9,
  38.7,
  18.0,
  25.0,
  'Driver & Passenger',
  'Front',
  '6',
  3.2,
  200.0,
  5500.0,
  2335.0,
  'Yes',
  18.0,
  5.0,
  195.0,
  115.0,
  71.0,
  38.0,
  30.0,
  15.0,
  3560.0,
  'non-USA',
  'Acura Legend'],
 ['Audi',
  '90',
  'Compact',
  25.9,
  29.1,
  32.3,
  20.0,
  26.0,
  'Driver only',
  'Front',
  '6',
  2.8,
  172.0,
  5500.0,
  2280.0,
  'Yes',
  16.9,
  5.0,
  180.0,
  102.0,
  67.0,
  37.0,
  28.0,
  14.0,
  3375.0,
  'non-USA',
  'Audi 90'],
 ['Audi',
  '100',
  'Midsize',
  nan,
  37.7,
  44.6,
  19.0,
  26.0,
  'Driver & Passenger',
  nan,
  '6',
  nan,
  172.0,
  5500.0,
  2535.0,
  nan,
  21.1,
  6.0,
  193.0,
  106.0,
  nan,
  37.0,
  31.0,
  17.0,
  3405.0,


In [97]:
#How to extract the row and column number of a particular cell with given criterion?
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

df.loc[df.Price == np.max(df.Price), ['Manufacturer', 'Model',' Type','Price']]

row, col = np.where(df.values == np.max(df.Price))
row, col

df.iat[row[0],col[0]]
df.iloc[row[0],col[0]]

df.at[row[0],'Price']
df.get_value(row[0],'Price')

Manufacturer Model   Type  Price
58  Mercedes-Benz  300E    NaN   61.9

(array([58], dtype=int64), array([4], dtype=int64))

61.899999999999999

61.899999999999999

61.899999999999999

61.899999999999999

In [103]:
#How to rename a specific columns in a dataframe?
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df = df.rename(columns={'Type': 'Cartype'})

# or
df.columns.values[2] = "CarType"

df.columns = df.columns.map(lambda x: x.replace('.', '_'))
df.columns

Index(['Manufacturer', 'Model', 'CarType', 'Min_Price', 'Price', 'Max_Price',
       'MPG_city', 'MPG_highway', 'AirBags', 'DriveTrain', 'Cylinders',
       'EngineSize', 'Horsepower', 'RPM', 'Rev_per_mile', 'Man_trans_avail',
       'Fuel_tank_capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
       'Turn_circle', 'Rear_seat_room', 'Luggage_room', 'Weight', 'Origin',
       'Make'],
      dtype='object')

In [107]:
#How to check if a dataframe has any missing values?
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

df.isnull().values.any()

True

In [109]:
#How to count the number of missing values in each column?
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

n_missing_each_col = df.apply(lambda x:x.isnull().sum())
n_missing_each_col

Manufacturer           4
Model                  1
Type                   3
Min.Price              7
Price                  2
Max.Price              5
MPG.city               9
MPG.highway            2
AirBags                6
DriveTrain             7
Cylinders              5
EngineSize             2
Horsepower             7
RPM                    3
Rev.per.mile           6
Man.trans.avail        5
Fuel.tank.capacity     8
Passengers             2
Length                 4
Wheelbase              1
Width                  6
Turn.circle            5
Rear.seat.room         4
Luggage.room          19
Weight                 7
Origin                 5
Make                   3
dtype: int64

In [111]:
#How to replace missing values of multiple numeric columns with the mean?
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

df_out = df[['Min.Price','Max.Price']] = df[['Min.Price','Max.Price']].apply(lambda x: x.fillna(x.mean()))
df_out.head()

Min.Price  Max.Price
0  12.900000  18.800000
1  29.200000  38.700000
2  25.900000  32.300000
3  17.118605  44.600000
4  17.118605  21.459091

In [115]:
#How to use apply function on existing columns with global variables as additional arguments?
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

d = {'Min.Price': np.nanmean, 'Max.Price': np.nanmedian}
df[['Min.Price', 'Max.Price']] = df[['Min.Price', 'Max.Price']].apply(lambda x, d: x.fillna(d[x.name](x)), args=(d, ))

In [125]:
#How to select a specific column from a dataframe as a dataframe instead of a series?
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))

type(df[['a']])
type(df.loc[:,['a','b']])
type(df.iloc[:,[0]])
df.loc[:,['a','b']]
#alternately the followting returns a series
type(df.a)
type(df['a'])
type(df.loc[:, 'a'])
type(df.iloc[:, 1])



pandas.core.frame.DataFrame

pandas.core.frame.DataFrame

pandas.core.frame.DataFrame

a   b
0   0   1
1   5   6
2  10  11
3  15  16

pandas.core.series.Series

pandas.core.series.Series

In [130]:
#How to change the order of columns of a dataframe?

df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))

df
df[list('cbade')]

df[sorted(df.columns)]
#or 
df.sort_index(axis = 1,ascending=False, inplace = True)


a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

c   b   a   d   e
0   2   1   0   3   4
1   7   6   5   8   9
2  12  11  10  13  14
3  17  16  15  18  19

a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

In [141]:
#How to set the number of rows and columns displayed in the output?
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

pd.set_option('display.max_columns', 10)
pd.set_option('display.max_rows',10)
df


Manufacturer    Model     Type  Min.Price  Price         ...          \
0         Acura  Integra    Small       12.9   15.9         ...           
1           NaN   Legend  Midsize       29.2   33.9         ...           
2          Audi       90  Compact       25.9   29.1         ...           
3          Audi      100  Midsize        NaN   37.7         ...           
4           BMW     535i  Midsize        NaN   30.0         ...           
..          ...      ...      ...        ...    ...         ...           
88   Volkswagen  Eurovan      Van       16.6   19.7         ...           
89   Volkswagen   Passat  Compact       17.6   20.0         ...           
90   Volkswagen  Corrado   Sporty       22.9   23.3         ...           
91        Volvo      240  Compact       21.8   22.7         ...           
92          NaN      850  Midsize       24.8   26.7         ...           

    Rear.seat.room  Luggage.room  Weight   Origin                Make  
0             26.5           NaN  2705.0  non-USA       Acura Integra  
1             30.0          15.0  3560.0  non-USA        Acura Legend  
2             28.0          14.0  3375.0  non-USA             Audi 90  
3             31.0          17.0  3405.0  non-USA            Audi 100  
4             27.0          13.0  3640.0  non-USA            BMW 535i  
..             ...           ...     ...      ...                 ...  
88            34.0           NaN  3960.0      NaN  Volkswagen Eurovan  
89            31.5          14.0  2985.0  non-USA   Volkswagen Passat  
90            26.0          15.0  2810.0  non-USA  Volkswagen Corrado  
91            29.5          14.0  2985.0  non-USA           Volvo 240  
92            30.0          15.0  3245.0  non-USA           Volvo 850  

[93 rows x 27 columns]

In [145]:
#How to format or suppress scientific notations in a pandas dataframe?
df = pd.DataFrame(np.random.random(4)**10, columns=['random'])
df

df.round(4)
df.apply(lambda x:'%.4f' %x, axis = 1)
#or
pd.set_option('display.float_format', lambda x: '%.4f' %x)
#reset /undo float format
pd.options.display.float_format = None


random
0  0.0000
1  0.0002
2  0.0006
3  0.0027

random
0  0.0000
1  0.0002
2  0.0006
3  0.0027

0    0.0000
1    0.0002
2    0.0006
3    0.0027
dtype: object

In [155]:
#How to format all the values in a dataframe as percentages?

df = pd.DataFrame(np.random.random(4), columns=['random'])
df
df.applymap(lambda x: str(round(x)**100) + '%')

out = df.style.format({'random':'{0:.2%}'.format})
out



random
0  0.4840
1  0.4213
2  0.6217
3  0.5436

random
0     0%
1     0%
2     1%
3     1%

In [157]:
#How to filter every nth row in a dataframe?
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

df.iloc[::20, :][['Manufacturer', 'Model', 'Type']]

Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small

In [159]:
#How to create a primary key index by combining relevant columns?
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv', usecols=[0,1,2,3,5])

df
df[['Manufacturer', 'Model', 'Type']] = df[['Manufacturer', 'Model', 'Type']].fillna('missing')
df.index = df.Manufacturer + '_' + df.Model + '_' + df.Type
df.index.is_unique

Manufacturer    Model     Type  Min.Price  Max.Price
0         Acura  Integra    Small    12.9000    18.8000
1           NaN   Legend  Midsize    29.2000    38.7000
2          Audi       90  Compact    25.9000    32.3000
3          Audi      100  Midsize        nan    44.6000
4           BMW     535i  Midsize        nan        nan
..          ...      ...      ...        ...        ...
88   Volkswagen  Eurovan      Van    16.6000    22.7000
89   Volkswagen   Passat  Compact    17.6000    22.4000
90   Volkswagen  Corrado   Sporty    22.9000    23.7000
91        Volvo      240  Compact    21.8000    23.5000
92          NaN      850  Midsize    24.8000    28.5000

[93 rows x 5 columns]

True

In [174]:
#How to get the row number of the nth largest value in a column?

df = pd.DataFrame(np.random.randint(1, 30, 30).reshape(10,-1), columns=list('abc'))
df
n=5
df['a'].argsort()[::-1][:4]


a   b   c
0  29  16   1
1   9  13  23
2   7  18  14
3   9  18  17
4  15  29  12
5  19   4  28
6  27  24  15
7  15  18  19
8  22  16   6
9  29  24  19

9    9
8    0
7    6
6    8
Name: a, dtype: int64

In [176]:
# How to find the position of the nth largest value greater than a given value?
ser = pd.Series(np.random.randint(1, 100, 15))
print('ser:' , ser.tolist(), 'mean', round(ser.mean()))

np.argwhere(ser > ser.mean())



ser: [49, 35, 77, 20, 85, 60, 6, 95, 45, 15, 47, 73, 97, 35, 38] mean 52


array([[ 2],
       [ 4],
       [ 5],
       [ 7],
       [11],
       [12]], dtype=int64)

In [190]:
#How to get the last n rows of a dataframe with row sum > 100?

df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
rowsums = df.apply(np.sum, axis = 1)
last_row = df.iloc[np.where(rowsums > 100)][[0]][-2:]
last_row

0
11  39
13  36

In [194]:
#How to find and cap outliers from a series or dataframe column?
ser = pd.Series(np.logspace(-2, 2, 30))
ser.quantile([0.05,0.95])
print ('-------')
def cap_outliers(ser, low_perc, high_perc):
    low, high = ser.quantile([low_perc,high_perc])
    low,high
    ser[ser < low] = low
    ser[ser > high] = high
    return (ser)
capped_ser = cap_outliers(ser, 0.05, 0.95)
capped_ser


0.0500    0.0160
0.9500   63.8767
dtype: float64

-------


0     0.0160
1     0.0160
2     0.0189
3     0.0259
4     0.0356
       ...  
25   28.0722
26   38.5662
27   52.9832
28   63.8767
29   63.8767
Length: 30, dtype: float64

In [204]:
#How to reshape a dataframe to the largest possible square after removing the negative values?
df = pd.DataFrame(np.random.randint(-20, 50, 100).reshape(10,-1))
#step 1 remove negative values
arr = df[df>0].values.flatten()
arr_qualified  = arr[~np.isnan(arr)]
arr_qualified
#step 2 find n
n = int(np.floor(arr_qualified.shape[0]**0.5))
#step 3 take n value and reshape
top_indexes = np.argsort(arr_qualified)[::-1]
output = np.take(arr_qualified, sorted(top_indexes[:n**2])).reshape(n,-1)
output

array([  2.,  20.,   3.,   2.,  19.,   2.,  25.,  16.,  32.,  48.,  17.,
        34.,   1.,  30.,  20.,  45.,  28.,  39.,  42.,  42.,  14.,  20.,
        42.,  25.,  17.,  11.,   7.,  17.,  47.,  42.,  10.,  27.,   4.,
        16.,   7.,   7.,  10.,  46.,   8.,  21.,  20.,  18.,  48.,  20.,
        34.,  49.,  43.,  41.,  41.,   5.,  45.,   7.,  49.,  38.,   1.,
        18.,  45.,   8.,  18.,  24.,  49.,  10.,  17.,  22.,  27.,  33.,
        34.,  24.])

array([[ 20.,   3.,  19.,   2.,  25.,  16.,  32.,  48.],
       [ 17.,  34.,  30.,  20.,  45.,  28.,  39.,  42.],
       [ 42.,  14.,  20.,  42.,  25.,  17.,  11.,   7.],
       [ 17.,  47.,  42.,  10.,  27.,   4.,  16.,   7.],
       [  7.,  10.,  46.,   8.,  21.,  20.,  18.,  48.],
       [ 20.,  34.,  49.,  43.,  41.,  41.,   5.,  45.],
       [  7.,  49.,  38.,  18.,  45.,   8.,  18.,  24.],
       [ 49.,  10.,  17.,  22.,  27.,  33.,  34.,  24.]])

In [206]:
#How to swap two rows of a dataframe?
df = pd.DataFrame(np.arange(25).reshape(5, -1))
df
def swap_row(df, i1, i2):
    a, b = df.iloc[i1,:].copy(), df.iloc[i2,:].copy()
    df.iloc[i1,:], df.iloc[i2,:] = b, a 
    return df

oupt = swap_row(df, 3,4)
oupt

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  20  21  22  23  24
4  15  16  17  18  19

In [208]:
#Reverse all the rows of dataframe df.
df = pd.DataFrame(np.arange(25).reshape(5, -1))
df
df.iloc[::-1,:]

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

0   1   2   3   4
4  20  21  22  23  24
3  15  16  17  18  19
2  10  11  12  13  14
1   5   6   7   8   9
0   0   1   2   3   4

In [213]:
# How to create one-hot encodings of a categorical variable (dummy variables)?
df = pd.DataFrame(np.arange(25).reshape(5,-1), columns=list('abcde'))

df
df_onehot = pd.concat([pd.get_dummies(df['a']), df[list('bcde')]], axis= 1)
df_onehot

a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

0  5  10  15  20   b   c   d   e
0  1  0   0   0   0   1   2   3   4
1  0  1   0   0   0   6   7   8   9
2  0  0   1   0   0  11  12  13  14
3  0  0   0   1   0  16  17  18  19
4  0  0   0   0   1  21  22  23  24

In [215]:
#Which column contains the highest number of row-wise maximum values?
df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1))
df
df.apply(np.argmax, axis = 1).value_counts().index[0]


0   1   2   3
0  42  36  41  95
1  58  47  71  60
2  58  91  88   7
3  67  40  93  96
4  60  91  26  85
5  84  60  47  29
6  84  99  48  41
7  13  63  61  20
8  99  62  44  51
9  13  14  98  54

1

In [221]:
#How to create a new column that contains the row number of nearest column by euclidean distance?
df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1), columns=list('pqrs'), index=list('abcdefghij'))
df
nearest_rows = []
nearest_distance = []

#iterate rows
for i, row  in df.iterrows():
    curr = row
    rest = df.drop(i)
    e_dists  ={}
    for j, contestant in rest.iterrows():
        #计算Euclidean距离
        e_dists.update({j:round(np.linalg.norm(curr.values - contestant.values))})
    nearest_rows.append(max(e_dists, key=e_dists.get))
    nearest_distance.append(max(e_dists.values()))

df['nearest_row'] = nearest_rows
df['dist'] = nearest_distance
df

p   q   r   s
a  83  32  70  49
b  35  38  19  15
c  48  85  69  63
d  61   5  47  41
e  35  14  54   8
f  65  48  37  85
g  74  55  80  36
h  41  82  14  18
i  90  94  56  71
j  20  98  71  38

p   q   r   s nearest_row     dist
a  83  32  70  49           j  92.0000
b  35  38  19  15           i 103.0000
c  48  85  69  63           e  92.0000
d  61   5  47  41           j 104.0000
e  35  14  54   8           i 116.0000
f  65  48  37  85           e  91.0000
g  74  55  80  36           h  81.0000
h  41  82  14  18           a  91.0000
i  90  94  56  71           e 116.0000
j  20  98  71  38           d 104.0000

In [226]:
#How to know the maximum possible correlation value of each column against other columns?
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1), columns=list('pqrstuvwxy'), index=list('abcdefgh'))
df
abs_corrmat = np.abs(df.corr())

max_corr = abs_corrmat.apply(lambda x : sorted(x)[-2])
abs_corrmat
max_corr
np.round(max_corr.tolist(),2)

p   q   r   s   t   u   v   w   x   y
a  76  70   9  32  91  96  78  73  41  36
b  60  76  12  86  42  92  91  22  81  30
c  44   8  69  41  90  65  51  64  55  10
d  33  92  99  32   8  61  59  47  21  98
e  98  28  13  30  63  65  12  64   1  79
f  75  68  80  94  17  67  62  12  22  95
g  97  14  62  89  60   9  90  57  30  42
h  32  54  73  50   6  92  27  99  24  48

p      q      r      s      t      u      v      w      x      y
p 1.0000 0.3825 0.5347 0.2783 0.4457 0.4456 0.1410 0.2116 0.2611 0.0822
q 0.3825 1.0000 0.0579 0.0068 0.5641 0.5407 0.2264 0.3442 0.1023 0.4730
r 0.5347 0.0579 1.0000 0.1048 0.5827 0.3660 0.0961 0.0417 0.2849 0.3732
s 0.2783 0.0068 0.1048 1.0000 0.2649 0.3258 0.5688 0.6267 0.3249 0.0222
t 0.4457 0.5641 0.5827 0.2649 1.0000 0.0759 0.1756 0.1951 0.2821 0.6456
u 0.4456 0.5407 0.3660 0.3258 0.0759 1.0000 0.2037 0.1275 0.3032 0.1285
v 0.1410 0.2264 0.0961 0.5688 0.1756 0.2037 1.0000 0.4847 0.6516 0.3106
w 0.2116 0.3442 0.0417 0.6267 0.1951 0.1275 0.4847 1.0000 0.2844 0.3354
x 0.2611 0.1023 0.2849 0.3249 0.2821 0.3032 0.6516 0.2844 1.0000 0.7163
y 0.0822 0.4730 0.3732 0.0222 0.6456 0.1285 0.3106 0.3354 0.7163 1.0000

p   0.5347
q   0.5641
r   0.5827
s   0.6267
t   0.6456
u   0.5407
v   0.6516
w   0.6267
x   0.7163
y   0.7163
dtype: float64

array([ 0.53,  0.56,  0.58,  0.63,  0.65,  0.54,  0.65,  0.63,  0.72,  0.72])

In [230]:
#How to create a column containing the minimum by maximum of each row?
df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1))
df
max_row = df.apply(lambda x :np.min(x)/np.max(x) ,axis=1)
max_row

0   1   2   3
0  26  70  53  20
1  94  53   3  16
2  37  38  12  79
3  48  29  47  89
4  73  50  61  83
5  93  85   1  73
6  47  68  13  12
7  78  79  69  57
8  81  27  86  37
9  77  17   8  31

0   0.2857
1   0.0319
2   0.1519
3   0.3258
4   0.6024
5   0.0108
6   0.1765
7   0.7215
8   0.3140
9   0.1039
dtype: float64

In [232]:
#How to create a column that contains the penultimate value in each row?
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))
df
row = df.apply(lambda x: sorted(x)[-2], axis= 1)
row

0   1   2   3   4   5   6   7   8   9
0  48  29  98  83  26   5  76  52  64  64
1  57  74  17  58  92  38  12   3  42  25
2  67  13  41   9  18   4  41  97  57  73
3  10  19  35  37   4  22  91  99  25  77
4  42  26  75  14  93  57  10  33  63  33
5  68   1  49  13  98  79  58  90  98  89
6  97  34  34  95  28   2   1   5   4  56
7  80  22  18  98  91  67  39  24  69  28

0    83
1    74
2    73
3    91
4    75
5    98
6    95
7    91
dtype: int64

In [235]:
#How to normalize all columns in a dataframe?
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))
df
out1 = df.apply(lambda x:((x - x.mean())/x.std()).round(2))
out1

0   1   2   3   4   5   6   7   8   9
0  96  41  55  13  48  70   4  59  99  78
1  78  14  89  25  70  48  10  47   3  30
2  64  61  42  52  52  89  28   2   2   1
3  19  83  31  68  78  99  55   9  80  95
4  25   2  71  35  64  25  74  44  34  38
5  28  63  20  50  76  67  27  71   6  48
6  71  66  23  75  53  56  94  79  76  35
7  39  55  22  49  26   2  58  23  68  59

0       1       2       3       4       5       6       7       8  \
0  1.5300 -0.2600  0.4300 -1.5800 -0.6000  0.4100 -1.2600  0.6100  1.3400   
1  0.9000 -1.2400  1.7600 -1.0000  0.6700 -0.2800 -1.0700  0.1900 -1.0900   
2  0.4000  0.4700 -0.0800  0.2900 -0.3700  1.0000 -0.5000 -1.4100 -1.1200   
3 -1.1800  1.2700 -0.5100  1.0600  1.1400  1.3100  0.3600 -1.1600  0.8600   
4 -0.9700 -1.6700  1.0500 -0.5200  0.3300 -1.0000  0.9600  0.0800 -0.3000   
5 -0.8600  0.5400 -0.9500  0.2000  1.0200  0.3100 -0.5300  1.0400 -1.0100   
6  0.6500  0.6500 -0.8300  1.4000 -0.3100 -0.0300  1.5900  1.3200  0.7600   
7 -0.4700  0.2500 -0.8700  0.1500 -1.8700 -1.7200  0.4500 -0.6600  0.5600   

        9  
0  1.0200  
1 -0.6100  
2 -1.6000  
3  1.6000  
4 -0.3400  
5  0.0000  
6 -0.4400  
7  0.3700

In [237]:
#How to compute the correlation of each row with the suceeding row?
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))
df
[df.iloc[i].corr(df.iloc[i+1]).round(2) for i in range(df.shape[0])[:-1]]

0   1   2   3   4   5   6   7   8   9
0  55  13  26   6   5  70  88  60  67  76
1  57  65  59  23  33  21  58  88   6  53
2  94  37  75   3  74  59  98  93  24  62
3  18  53  20  89  69  36  50  69  81  67
4  51  68  79  68  69  68  55  85  71  43
5  69  23  57  19  57  98  23  20  80  15
6  91  59  32  68  92  44  32  21  79  74
7  15  60  46  33  21  36  83  25  71   2

[0.080000000000000002,
 0.64000000000000001,
 -0.58999999999999997,
 0.12,
 0.14000000000000001,
 0.23000000000000001,
 -0.35999999999999999]

In [242]:
#How to replace both the diagonals of dataframe with 0?
df = pd.DataFrame(np.random.randint(1,100, 100).reshape(10, -1))
df
for i in range(df.shape[0]):
    df.iloc[i,i] = 0
    df.iloc[df.shape[0] - i-1, i] = 0
    
df

0   1   2   3   4   5   6   7   8   9
0  34  90  25  44  83  39  72  56  66  77
1  39  17  29  31  92  33  88  83  77  15
2  82  99  68  37  17   1  88  29  41  80
3  68  43  61  34  16  43  63  41  63  35
4  23  35  33  80  41  68   7  55  27  70
5  38  28  51  31  94  51  20  98  89  96
6  48  50   2  75  25  90  16  13  31  82
7  78  68  28  66  89  74  23  94  85  86
8  29  59  62   7  65  93  83  26  67  29
9  46  86  13   4  51  72  67  76  44   2

0   1   2   3   4   5   6   7   8   9
0   0  90  25  44  83  39  72  56  66   0
1  39   0  29  31  92  33  88  83   0  15
2  82  99   0  37  17   1  88   0  41  80
3  68  43  61   0  16  43   0  41  63  35
4  23  35  33  80   0   0   7  55  27  70
5  38  28  51  31   0   0  20  98  89  96
6  48  50   2   0  25  90   0  13  31  82
7  78  68   0  66  89  74  23   0  85  86
8  29   0  62   7  65  93  83  26   0  29
9   0  86  13   4  51  72  67  76  44   0

In [247]:
#How to get the particular group of a groupby dataframe by key?
df = pd.DataFrame({'col1': ['apple', 'banana', 'orange'] * 3,
                   'col2': np.random.rand(9),
                   'col3': np.random.randint(0, 15, 9)})

df_grouped = df.groupby(['col1'])

df_grouped.get_group('apple')


col1   col2  col3
0  apple 0.2969     9
3  apple 0.6938     5
6  apple 0.6811    11

In [254]:
# How to get the n’th largest value of a column when grouped by another column?
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'rating': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})
df_grouped = df.groupby('fruit')['price']
df_grouped.get_group('banana').sort_values().iloc[-2]


10

In [257]:
#How to join two dataframes by 2 columns so they have only the common rows?
df1 = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                    'weight': ['high', 'medium', 'low'] * 3,
                    'price': np.random.randint(0, 15, 9)})

df2 = pd.DataFrame({'pazham': ['apple', 'orange', 'pine'] * 2,
                    'kilo': ['high', 'low'] * 3,
                    'price': np.random.randint(0, 15, 6)})

df = pd.merge(df1, df2, how='inner', left_on=['fruit', 'weight'], right_on=['pazham', 'kilo'], suffixes=['_left', '_right'])
df


fruit  price_left weight  kilo  pazham  price_right
0   apple           3   high  high   apple            3
1   apple           9   high  high   apple            3
2   apple           4   high  high   apple            3
3  orange           5    low   low  orange           12
4  orange           6    low   low  orange           12
5  orange           4    low   low  orange           12

In [259]:
#How to remove rows from a dataframe that are present in another dataframe?
df1 = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                    'weight': ['high', 'medium', 'low'] * 3,
                    'price': np.random.randint(0, 15, 9)})

df2 = pd.DataFrame({'pazham': ['apple', 'orange', 'pine'] * 2,
                    'kilo': ['high', 'low'] * 3,
                    'price': np.random.randint(0, 15, 6)})

df1[~df1.isin(df2).all(1)]


fruit  price  weight
0   apple      9    high
1  banana      9  medium
2  orange     14     low
3   apple      4    high
4  banana      0  medium
5  orange      9     low
6   apple      8    high
7  banana      1  medium
8  orange     14     low

In [262]:
#How to get the positions where values of two columns match?

df = pd.DataFrame({'fruit1': np.random.choice(['apple', 'orange', 'banana'], 10),
                    'fruit2': np.random.choice(['apple', 'orange', 'banana'], 10)})

df
np.where(df.fruit1 == df.fruit2)

fruit1  fruit2
0  banana  banana
1  banana   apple
2  banana   apple
3  banana   apple
4   apple   apple
5   apple  banana
6  banana   apple
7   apple   apple
8  orange  orange
9   apple  banana

(array([0, 4, 7, 8], dtype=int64),)

In [264]:
#How to create lags and leads of a column in a dataframe?
df = pd.DataFrame(np.random.randint(1, 100, 20).reshape(-1, 4), columns = list('abcd'))
df
df['a_lag1'] = df['a'].shift(1)
df['b_lead1'] = df['b'].shift(-1)
df

a   b   c   d
0  11  10  77  19
1  29  33  37  81
2  86  43  94  84
3   6  12  50  81
4  73  88  79  22

a   b   c   d  a_lag1  b_lead1
0  11  10  77  19     nan  33.0000
1  29  33  37  81 11.0000  43.0000
2  86  43  94  84 29.0000  12.0000
3   6  12  50  81 86.0000  88.0000
4  73  88  79  22  6.0000      nan

In [269]:
#How to get the frequency of unique values in the entire dataframe?
df = pd.DataFrame(np.random.randint(1, 10, 20).reshape(-1, 4), columns = list('abcd'))
df
pd.value_counts(df.values.ravel())
#Return the flattened underlying data as an ndarray (ravel)

a  b  c  d
0  1  4  6  3
1  9  9  4  3
2  2  3  2  2
3  6  4  9  6
4  3  5  7  2

3    4
2    4
9    3
6    3
4    3
7    1
5    1
1    1
dtype: int64

In [272]:
#How to split a text column into two separate columns?
df = pd.DataFrame(["STD, City    State",
"33, Kolkata    West Bengal",
"44, Chennai    Tamil Nadu",
"40, Hyderabad    Telengana",
"80, Bangalore    Karnataka"], columns=['row'])
df
df_out = df.row.str.split(',|\t', expand = True)
df_out
new_header= df_out.iloc[0]
df_out = df_out[1:]
df_out.columns = new_header
df_out

row
0          STD, City    State
1  33, Kolkata    West Bengal
2   44, Chennai    Tamil Nadu
3  40, Hyderabad    Telengana
4  80, Bangalore    Karnataka

0                        1
0  STD            City    State
1   33   Kolkata    West Bengal
2   44    Chennai    Tamil Nadu
3   40   Hyderabad    Telengana
4   80   Bangalore    Karnataka

0 STD            City    State
1  33   Kolkata    West Bengal
2  44    Chennai    Tamil Nadu
3  40   Hyderabad    Telengana
4  80   Bangalore    Karnataka