In [275]:
# import module
import pandas as pd
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [276]:
#How to convert the index of a series into a column of a dataframe?
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)

ser1 = pd.Series(mylist)
ser2 = pd.Series(myarr)
ser3 = pd.Series(mydict)

ser1, ser2, ser3

(0     a
 1     b
 2     c
 3     e
 4     d
      ..
 21    v
 22    w
 23    x
 24    y
 25    z
 Length: 26, dtype: object, 0      0
 1      1
 2      2
 3      3
 4      4
       ..
 21    21
 22    22
 23    23
 24    24
 25    25
 Length: 26, dtype: int32, a     0
 b     1
 c     2
 d     4
 e     3
      ..
 v    21
 w    22
 x    23
 y    24
 z    25
 Length: 26, dtype: int64)

In [277]:
#. How to convert the index of a series into a column of a dataframe?
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)

df = ser.to_frame().reset_index()
df.head()

index  0
0     a  0
1     b  1
2     c  2
3     d  4
4     e  3

In [278]:
#  How to combine many series to form a dataframe?
import numpy as np
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))

df = pd.concat([ser1,ser2],axis = 1)
df = pd.DataFrame({'col1':ser1,'col2':ser2})
df.head()

col1  col2
0    a     0
1    b     1
2    c     2
3    e     3
4    d     4

In [279]:
#How to assign name to the series’ index?
ser = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))

ser.name = 'alphabets'
ser.head()

0    a
1    b
2    c
3    e
4    d
Name: alphabets, dtype: object

In [280]:
#How to get the items of series A not present in series B?
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

ser1 = ser1[~ser1.isin(ser2)]
ser1.head()

0    1
1    2
2    3
dtype: int64

In [281]:
#How to get the items not common to both series A and series B
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

ser_u = pd.Series(np.union1d(ser1,ser2))
ser_i = pd.Series(np.intersect1d(ser1,ser2))

ser_u
ser_i
ser = ser_u[~ser_u.isin(ser_i)]
ser

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
dtype: int64

0    4
1    5
dtype: int64

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64

In [282]:
#How to get the minimum, 25th percentile, median, 75th, and max of a numeric series?
ser = pd.Series(np.random.normal(10, 5, 25))

np.percentile(ser,  q=[0, 25, 50, 75, 100])
ser.describe()

array([  1.82539732,   9.23459626,  11.66158143,  15.52105388,  21.5895596 ])

count   25.0000
mean    11.9176
std      4.4696
min      1.8254
25%      9.2346
50%     11.6616
75%     15.5211
max     21.5896
dtype: float64

In [283]:
#How to get frequency counts of unique items of a series?
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))

ser_unique = pd.Series(ser.unique()).count()

ser.value_counts()

c    6
d    6
f    5
g    4
e    3
h    3
a    2
b    1
dtype: int64

In [284]:
# How to keep only top 2 most frequent values as it is and replace everything else as ‘Other’?
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))

ser.value_counts().index[:2]
ser.value_counts()
ser[~ser.isin(ser.value_counts().index[:2])] = 'Other'
ser

Int64Index([2, 4], dtype='int64')

2    4
4    3
3    3
1    2
dtype: int64

0         2
1         4
2     Other
3     Other
4     Other
      ...  
7         2
8     Other
9         2
10        4
11        4
Length: 12, dtype: object

In [285]:
#How to bin a numeric series to 10 groups of equal size?
ser = pd.Series(np.random.random(20))

pd.qcut(ser, q = [0, .10, .20, .3, .4, .5, .6, .7, .8, .9, 1], 
        labels=['1st', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th', '9th', '10th']).head()

0    2nd
1    6th
2    8th
3    4th
4    5th
dtype: category
Categories (10, object): [1st < 2nd < 3rd < 4th ... 7th < 8th < 9th < 10th]

In [286]:
#How to convert a numpy array to a dataframe of given shape? (L1)
ser = pd.Series(np.random.randint(1, 10, 35))

type(ser.values.reshape(7,5))
df = pd.DataFrame(ser.values.reshape(7,5))
df

numpy.ndarray

0  1  2  3  4
0  4  9  5  3  9
1  6  1  2  1  5
2  7  7  5  8  1
3  9  5  2  7  7
4  9  1  8  3  9
5  9  7  8  1  3
6  2  3  5  9  2

In [287]:
#How to find the positions of numbers that are multiples of 3 from a series?
ser = pd.Series(np.random.randint(1, 10, 7))

ser
np.argwhere(ser % 3 == 0)

0    3
1    3
2    8
3    3
4    8
5    8
6    2
dtype: int32

array([[0],
       [1],
       [3]], dtype=int64)

In [288]:
#How to extract items at given positions from a series
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]

ser.take(pos)

0     a
4     e
8     i
14    o
20    u
dtype: object

In [289]:
# How to stack two series vertically and horizontally ?
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))

pd.concat([ser1,ser2] , axis = 1)
pd.concat([ser1,ser2],axis = 0)
#or 
ser1.append(ser2)

0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e

0    0
1    1
2    2
3    3
4    4
0    a
1    b
2    c
3    d
4    e
dtype: object

0    0
1    1
2    2
3    3
4    4
0    a
1    b
2    c
3    d
4    e
dtype: object

In [290]:
#How to get the positions of items of series A in another series B?
ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])

[np.where(i ==ser1)[0].tolist()[0] for i in ser2]
#or
[pd.Index(ser1).get_loc(i) for i in ser2]

[5, 4, 0, 8]

[5, 4, 0, 8]

In [291]:
#How to compute the mean squared error on a truth and predicted series?
truth = pd.Series(range(10))
pred = pd.Series(range(10)) + np.random.random(10)

np.mean((truth - pred)**2)

0.2086940081867402

In [292]:
# How to convert the first character of each element in a series to uppercase?
ser = pd.Series(['how', 'to', 'kick', 'ass?'])

pd.Series([i.title() for i in ser])
#or 
ser.map(lambda x : x.title())
#lambda argument: manipulate(argument) 

0     How
1      To
2    Kick
3    Ass?
dtype: object

0     How
1      To
2    Kick
3    Ass?
dtype: object

In [293]:
#How to calculate the number of characters in each word in a series?
ser = pd.Series(['how', 'to', 'kick', 'ass?'])

pd.Series([len(i) for i in ser])
ser.map(lambda i : len(i))

0    3
1    2
2    4
3    4
dtype: int64

0    3
1    2
2    4
3    4
dtype: int64

In [294]:
# How to compute difference of differences between consequtive numbers of a series?
ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])

ser.diff().tolist()
ser.diff().diff().tolist()


[nan, 2.0, 3.0, 4.0, 5.0, 6.0, 6.0, 8.0]

[nan, nan, 1.0, 1.0, 1.0, 1.0, 0.0, 2.0]

In [295]:
#How to convert a series of date-strings to a timeseries?
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

pd.to_datetime(ser)

0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]

In [296]:
#How to get the day of month, week number, day of year and day of week from a series of date strings?
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

#solution 
from dateutil.parser import parse
ser_ts = ser.map(lambda x: parse(x))
#year
print(ser_ts.dt.day.tolist())
ser_ts.dt.weekofyear.tolist()
ser_ts.dt.dayofyear.tolist()
ser_ts.dt.weekday_name.tolist()

[1, 2, 3, 4, 5, 6]


[53, 5, 9, 14, 19, 23]

[1, 33, 63, 94, 125, 157]

['Friday', 'Wednesday', 'Saturday', 'Thursday', 'Monday', 'Saturday']

In [297]:
#How to convert year-month string to dates corresponding to the 4th day of the month?
ser = pd.Series(['Jan 2010', 'Feb 2011', 'Mar 2012'])

#solution 1 
from dateutil.parser import parse
ser_dt = ser.map(lambda i : parse(i))

ser_datestr = ser_dt.dt.year.astype('str') + '-' + ser_dt.dt.month.astype('str') + '-' + '04'
ser_datestr


0    2010-1-04
1    2011-2-04
2    2012-3-04
dtype: object

In [298]:
#How to filter words that contain atleast 2 vowels from a series?
ser = pd.Series(['Apple', 'Orange', 'Plan', 'Python', 'Money'])

vowel = ['a','e','i','u','o']

from collections import Counter
mask = ser.map(lambda x : sum([Counter(x.lower()).get(i,0) for i in list('aeiou')]) >= 2)
ser[mask]



0     Apple
1    Orange
4     Money
dtype: object

In [299]:
#How to filter valid emails from a series?
emails = pd.Series(['buying books at amazom.com', 'rameses@egypt.com', 'matt@t.co', 'narendra@modi.com'])
pattern ='[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'

import re

mask = emails.map(lambda x: bool(re.match(pattern, x)))
emails[mask]

emails.str.findall(pattern, flags = re.IGNORECASE)



1    rameses@egypt.com
2            matt@t.co
3    narendra@modi.com
dtype: object

0                     []
1    [rameses@egypt.com]
2            [matt@t.co]
3    [narendra@modi.com]
dtype: object

In [300]:
#How to get the mean of a series grouped by another series?
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))
print(weights.tolist())
print(fruit.tolist())

pd_data = pd.concat([fruit,weights],axis = 1)
pd_data.groupby(0).mean()
#or 

weights.groupby(fruit).mean()

[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
['carrot', 'apple', 'banana', 'banana', 'carrot', 'banana', 'apple', 'apple', 'carrot', 'banana']


1
0            
apple  5.6667
banana 5.7500
carrot 5.0000

apple    5.6667
banana   5.7500
carrot   5.0000
dtype: float64

In [301]:
#How to compute the euclidean distance between two series?
p = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
q = pd.Series([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])

sum((p-q)**2)**0.5

#or
np.linalg.norm(p-q)

18.165902124584949

18.165902124584949

In [302]:
#How to find all the local maxima (or peaks) in a numeric series?
ser = pd.Series([2, 10, 3, 4, 9, 10, 2, 7, 3])

dd = np.diff(np.sign(np.diff(ser)))
peak_locs = np.where(dd == -2)[0] +1
peak_locs


array([1, 5, 7], dtype=int64)

In [303]:
#How to replace missing spaces in a string with the least frequent character?
my_str = 'dbc deb abed gade'

from collections import Counter
ser = pd.Series(list(my_str))

freq = ser.value_counts()
freq
least_freq = freq.dropna().index[-1]
least_freq
''.join(ser.replace(' ',least_freq))



d    4
     3
b    3
e    3
a    2
c    1
g    1
dtype: int64

'g'

'dbcgdebgabedggade'

In [304]:
#How to create a TimeSeries starting ‘2000-01-01’ and 10 weekends (saturdays) after that having random numbers as values?
ser = pd.Series(np.random.randint(1,10,10), pd.date_range('2000-01-01', periods=10,freq = 'W-SAT'))
ser

2000-01-01    5
2000-01-08    3
2000-01-15    8
2000-01-22    5
2000-01-29    1
2000-02-05    4
2000-02-12    7
2000-02-19    5
2000-02-26    2
2000-03-04    5
Freq: W-SAT, dtype: int32

In [305]:
#How to fill an intermittent time series so all missing dates show up with values of previous non-missing date?
ser = pd.Series([1,10,3,np.nan], index=pd.to_datetime(['2000-01-01', '2000-01-03', '2000-01-06', '2000-01-08']))
ser
ser.resample('D').ffill() 
# alternatives
ser.resample('D').bfill()  #fill with next value
ser.resample('D').bfill().ffill()    #fill next else prev value


2000-01-01    1.0000
2000-01-03   10.0000
2000-01-06    3.0000
2000-01-08       nan
dtype: float64

2000-01-01    1.0000
2000-01-02    1.0000
2000-01-03   10.0000
2000-01-04   10.0000
2000-01-05   10.0000
2000-01-06    3.0000
2000-01-07    3.0000
2000-01-08       nan
Freq: D, dtype: float64

2000-01-01    1.0000
2000-01-02   10.0000
2000-01-03   10.0000
2000-01-04    3.0000
2000-01-05    3.0000
2000-01-06    3.0000
2000-01-07       nan
2000-01-08       nan
Freq: D, dtype: float64

2000-01-01    1.0000
2000-01-02   10.0000
2000-01-03   10.0000
2000-01-04    3.0000
2000-01-05    3.0000
2000-01-06    3.0000
2000-01-07    3.0000
2000-01-08    3.0000
Freq: D, dtype: float64

In [306]:
#How to compute the autocorrelations of a numeric series?
ser = pd.Series(np.arange(20) + np.random.normal(1, 10, 20))

autocorrelations = [ser.autocorr(i).round(2) for i in range(11)]
autocorrelations[1:]
np.argmax(np.abs(autocorrelations[1:])) + 1

[0.26000000000000001,
 0.34000000000000002,
 0.22,
 0.13,
 0.28999999999999998,
 0.20000000000000001,
 0.41999999999999998,
 0.17000000000000001,
 -0.23999999999999999,
 -0.54000000000000004]

10

In [307]:
#How to import only every nth row from a csv file to create a dataframe
df= pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', chunksize=50)

df2 = pd.DataFrame()

for chunk in df:
    df2 = df2.append(chunk.iloc[0,:])
    
df2

age        b   chas    crim    dis   ...    ptratio     rad     rm  \
0    65.2000 396.9000 0.0000  0.0063 4.0900   ...    15.3000  1.0000 6.5750   
50   45.7000 395.5600 0.0000  0.0887 6.8147   ...    16.8000  4.0000 5.9630   
100  79.9000 394.7600 0.0000  0.1487 2.7778   ...    20.9000  5.0000 6.7270   
150  97.3000 372.8000 0.0000  1.6566 1.6180   ...    14.7000  5.0000 6.1220   
200  13.9000 384.3000 0.0000  0.0178 7.6534   ...    17.0000  3.0000 7.1350   
..       ...      ...    ...     ...    ...   ...        ...     ...    ...   
300  47.4000 390.8600 0.0000  0.0442 7.8278   ...    14.8000  5.0000 6.8710   
350  44.4000 396.9000 0.0000  0.0621 8.7921   ...    19.7000  1.0000 6.4900   
400 100.0000 396.9000 0.0000 25.0461 1.5888   ...    20.2000 24.0000 5.9870   
450  92.6000   0.3200 0.0000  6.7177 2.3236   ...    20.2000 24.0000 6.7490   
500  79.7000 396.9000 0.0000  0.2244 2.4982   ...    19.2000  6.0000 6.0270   

         tax      zn  
0   296.0000 18.0000  
50  243.0000 21.0000  
100 384.0000  0.0000  
150 403.0000  0.0000  
200 402.0000 95.0000  
..       ...     ...  
300 358.0000 70.0000  
350 335.0000 40.0000  
400 666.0000  0.0000  
450 666.0000  0.0000  
500 391.0000  0.0000  

[11 rows x 14 columns]

In [308]:
#How to change column values when importing csv to a dataframe?

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', 
                 converters={'medv': lambda x: 'High' if float(x) > 25 else 'Low'})

df


crim      zn   indus  chas    nox  ...   tax  ptratio        b  lstat  \
0   0.0063 18.0000  2.3100     0 0.5380  ...   296  15.3000 396.9000 4.9800   
1   0.0273  0.0000  7.0700     0 0.4690  ...   242  17.8000 396.9000 9.1400   
2   0.0273  0.0000  7.0700     0 0.4690  ...   242  17.8000 392.8300 4.0300   
3   0.0324  0.0000  2.1800     0 0.4580  ...   222  18.7000 394.6300 2.9400   
4   0.0691  0.0000  2.1800     0 0.4580  ...   222  18.7000 396.9000 5.3300   
..     ...     ...     ...   ...    ...  ...   ...      ...      ...    ...   
501 0.0626  0.0000 11.9300     0 0.5730  ...   273  21.0000 391.9900 9.6700   
502 0.0453  0.0000 11.9300     0 0.5730  ...   273  21.0000 396.9000 9.0800   
503 0.0608  0.0000 11.9300     0 0.5730  ...   273  21.0000 396.9000 5.6400   
504 0.1096  0.0000 11.9300     0 0.5730  ...   273  21.0000 393.4500 6.4800   
505 0.0474  0.0000 11.9300     0 0.5730  ...   273  21.0000 396.9000 7.8800   

     medv  
0     Low  
1     Low  
2    High  
3    High  
4    High  
..    ...  
501   Low  
502   Low  
503   Low  
504   Low  
505   Low  

[506 rows x 14 columns]

In [309]:
# How to create a dataframe with rows as strides from a given series?
L = pd.Series(range(15))

def gen_strides(a, stride_len = 5, window_len = 5):
    n_strides = ((a.size - window_len)//stride_len) + 1
    return np.array([a[s:(s+window_len)] for s in np.arange(0, a.size, stride_len)[:n_strides]])
gen_strides(L, stride_len=2, window_len=4)



array([[ 0,  1,  2,  3],
       [ 2,  3,  4,  5],
       [ 4,  5,  6,  7],
       [ 6,  7,  8,  9],
       [ 8,  9, 10, 11],
       [10, 11, 12, 13]])

In [310]:
# How to import only specified columns from a csv file?
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', usecols=['crim', 'medv'])
print(df.head())

    crim    medv
0 0.0063 24.0000
1 0.0273 21.6000
2 0.0273 34.7000
3 0.0324 33.4000
4 0.0691 36.2000


In [311]:
#How to get the nrows, ncolumns, datatype, summary stats of each column of a dataframe? Also get the array and list equivalent
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

df.shape

df.dtypes

df.get_dtype_counts()

df.dtypes.value_counts()

df.describe()

df.values

df.values.tolist()

(93, 27)

Manufacturer       object
Model              object
Type               object
Min.Price         float64
Price             float64
                   ...   
Rear.seat.room    float64
Luggage.room      float64
Weight            float64
Origin             object
Make               object
Length: 27, dtype: object

float64    18
object      9
dtype: int64

float64    18
object      9
dtype: int64

Min.Price   Price  Max.Price  MPG.city  MPG.highway    ...      Width  \
count    86.0000 91.0000    88.0000   84.0000      91.0000    ...    87.0000   
mean     17.1186 19.6165    21.4591   22.4048      29.0659    ...    69.4483   
std       8.8283  9.7243    10.6966    5.8415       5.3703    ...     3.7780   
min       6.7000  7.4000     7.9000   15.0000      20.0000    ...    60.0000   
25%      10.8250 12.3500    14.5750   18.0000      26.0000    ...    67.0000   
50%      14.6000 17.7000    19.1500   21.0000      28.0000    ...    69.0000   
75%      20.2500 23.5000    24.8250   25.0000      31.0000    ...    72.0000   
max      45.4000 61.9000    80.0000   46.0000      50.0000    ...    78.0000   

       Turn.circle  Rear.seat.room  Luggage.room    Weight  
count      88.0000         89.0000       74.0000   86.0000  
mean       38.9545         27.8539       13.9865 3104.5930  
std         3.3042          3.0181        3.1208  600.1300  
min        32.0000         19.0000        6.0000 1695.0000  
25%        36.0000         26.0000       12.0000 2647.5000  
50%        39.0000         27.5000       14.0000 3085.0000  
75%        42.0000         30.0000       16.0000 3567.5000  
max        45.0000         36.0000       22.0000 4105.0000  

[8 rows x 18 columns]

array([['Acura', 'Integra', 'Small', ..., 2705.0, 'non-USA',
        'Acura Integra'],
       [nan, 'Legend', 'Midsize', ..., 3560.0, 'non-USA', 'Acura Legend'],
       ['Audi', '90', 'Compact', ..., 3375.0, 'non-USA', 'Audi 90'],
       ..., 
       ['Volkswagen', 'Corrado', 'Sporty', ..., 2810.0, 'non-USA',
        'Volkswagen Corrado'],
       ['Volvo', '240', 'Compact', ..., 2985.0, 'non-USA', 'Volvo 240'],
       [nan, '850', 'Midsize', ..., 3245.0, 'non-USA', 'Volvo 850']], dtype=object)

[['Acura',
  'Integra',
  'Small',
  12.9,
  15.9,
  18.8,
  25.0,
  31.0,
  'None',
  'Front',
  '4',
  1.8,
  140.0,
  6300.0,
  2890.0,
  'Yes',
  13.2,
  5.0,
  177.0,
  102.0,
  68.0,
  37.0,
  26.5,
  nan,
  2705.0,
  'non-USA',
  'Acura Integra'],
 [nan,
  'Legend',
  'Midsize',
  29.2,
  33.9,
  38.7,
  18.0,
  25.0,
  'Driver & Passenger',
  'Front',
  '6',
  3.2,
  200.0,
  5500.0,
  2335.0,
  'Yes',
  18.0,
  5.0,
  195.0,
  115.0,
  71.0,
  38.0,
  30.0,
  15.0,
  3560.0,
  'non-USA',
  'Acura Legend'],
 ['Audi',
  '90',
  'Compact',
  25.9,
  29.1,
  32.3,
  20.0,
  26.0,
  'Driver only',
  'Front',
  '6',
  2.8,
  172.0,
  5500.0,
  2280.0,
  'Yes',
  16.9,
  5.0,
  180.0,
  102.0,
  67.0,
  37.0,
  28.0,
  14.0,
  3375.0,
  'non-USA',
  'Audi 90'],
 ['Audi',
  '100',
  'Midsize',
  nan,
  37.7,
  44.6,
  19.0,
  26.0,
  'Driver & Passenger',
  nan,
  '6',
  nan,
  172.0,
  5500.0,
  2535.0,
  nan,
  21.1,
  6.0,
  193.0,
  106.0,
  nan,
  37.0,
  31.0,
  17.0,
  3405.0,


In [312]:
#How to extract the row and column number of a particular cell with given criterion?
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

df.loc[df.Price == np.max(df.Price), ['Manufacturer', 'Model',' Type','Price']]

row, col = np.where(df.values == np.max(df.Price))
row, col

df.iat[row[0],col[0]]
df.iloc[row[0],col[0]]

df.at[row[0],'Price']
df.get_value(row[0],'Price')

Manufacturer Model   Type   Price
58  Mercedes-Benz  300E    nan 61.9000

(array([58], dtype=int64), array([4], dtype=int64))

61.899999999999999

61.899999999999999

61.899999999999999

61.899999999999999

In [313]:
#How to rename a specific columns in a dataframe?
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df = df.rename(columns={'Type': 'Cartype'})

# or
df.columns.values[2] = "CarType"

df.columns = df.columns.map(lambda x: x.replace('.', '_'))
df.columns

Index(['Manufacturer', 'Model', 'CarType', 'Min_Price', 'Price', 'Max_Price',
       'MPG_city', 'MPG_highway', 'AirBags', 'DriveTrain', 'Cylinders',
       'EngineSize', 'Horsepower', 'RPM', 'Rev_per_mile', 'Man_trans_avail',
       'Fuel_tank_capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
       'Turn_circle', 'Rear_seat_room', 'Luggage_room', 'Weight', 'Origin',
       'Make'],
      dtype='object')

In [314]:
#How to check if a dataframe has any missing values?
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

df.isnull().values.any()

True

In [315]:
#How to count the number of missing values in each column?
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

n_missing_each_col = df.apply(lambda x:x.isnull().sum())
n_missing_each_col

Manufacturer       4
Model              1
Type               3
Min.Price          7
Price              2
                  ..
Rear.seat.room     4
Luggage.room      19
Weight             7
Origin             5
Make               3
Length: 27, dtype: int64

In [316]:
#How to replace missing values of multiple numeric columns with the mean?
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

df_out = df[['Min.Price','Max.Price']] = df[['Min.Price','Max.Price']].apply(lambda x: x.fillna(x.mean()))
df_out.head()

Min.Price  Max.Price
0    12.9000    18.8000
1    29.2000    38.7000
2    25.9000    32.3000
3    17.1186    44.6000
4    17.1186    21.4591

In [317]:
#How to use apply function on existing columns with global variables as additional arguments?
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

d = {'Min.Price': np.nanmean, 'Max.Price': np.nanmedian}
df[['Min.Price', 'Max.Price']] = df[['Min.Price', 'Max.Price']].apply(lambda x, d: x.fillna(d[x.name](x)), args=(d, ))

In [318]:
#How to select a specific column from a dataframe as a dataframe instead of a series?
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))

type(df[['a']])
type(df.loc[:,['a','b']])
type(df.iloc[:,[0]])
df.loc[:,['a','b']]
#alternately the followting returns a series
type(df.a)
type(df['a'])
type(df.loc[:, 'a'])
type(df.iloc[:, 1])



pandas.core.frame.DataFrame

pandas.core.frame.DataFrame

pandas.core.frame.DataFrame

a   b
0   0   1
1   5   6
2  10  11
3  15  16

pandas.core.series.Series

pandas.core.series.Series

pandas.core.series.Series

pandas.core.series.Series

In [319]:
#How to change the order of columns of a dataframe?

df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))

df
df[list('cbade')]

df[sorted(df.columns)]
#or 
df.sort_index(axis = 1,ascending=False, inplace = True)


a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

c   b   a   d   e
0   2   1   0   3   4
1   7   6   5   8   9
2  12  11  10  13  14
3  17  16  15  18  19

a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

In [320]:
#How to set the number of rows and columns displayed in the output?
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

pd.set_option('display.max_columns', 10)
pd.set_option('display.max_rows',10)
df


Manufacturer    Model     Type  Min.Price   Price         ...          \
0         Acura  Integra    Small    12.9000 15.9000         ...           
1           NaN   Legend  Midsize    29.2000 33.9000         ...           
2          Audi       90  Compact    25.9000 29.1000         ...           
3          Audi      100  Midsize        nan 37.7000         ...           
4           BMW     535i  Midsize        nan 30.0000         ...           
..          ...      ...      ...        ...     ...         ...           
88   Volkswagen  Eurovan      Van    16.6000 19.7000         ...           
89   Volkswagen   Passat  Compact    17.6000 20.0000         ...           
90   Volkswagen  Corrado   Sporty    22.9000 23.3000         ...           
91        Volvo      240  Compact    21.8000 22.7000         ...           
92          NaN      850  Midsize    24.8000 26.7000         ...           

    Rear.seat.room  Luggage.room    Weight   Origin                Make  
0          26.5000           nan 2705.0000  non-USA       Acura Integra  
1          30.0000       15.0000 3560.0000  non-USA        Acura Legend  
2          28.0000       14.0000 3375.0000  non-USA             Audi 90  
3          31.0000       17.0000 3405.0000  non-USA            Audi 100  
4          27.0000       13.0000 3640.0000  non-USA            BMW 535i  
..             ...           ...       ...      ...                 ...  
88         34.0000           nan 3960.0000      NaN  Volkswagen Eurovan  
89         31.5000       14.0000 2985.0000  non-USA   Volkswagen Passat  
90         26.0000       15.0000 2810.0000  non-USA  Volkswagen Corrado  
91         29.5000       14.0000 2985.0000  non-USA           Volvo 240  
92         30.0000       15.0000 3245.0000  non-USA           Volvo 850  

[93 rows x 27 columns]

In [321]:
#How to format or suppress scientific notations in a pandas dataframe?
df = pd.DataFrame(np.random.random(4)**10, columns=['random'])
df

df.round(4)
df.apply(lambda x:'%.4f' %x, axis = 1)
#or
pd.set_option('display.float_format', lambda x: '%.4f' %x)
#reset /undo float format
pd.options.display.float_format = None


random
0  0.0022
1  0.6093
2  0.0000
3  0.0083

random
0  0.0022
1  0.6093
2  0.0000
3  0.0083

0    0.0022
1    0.6093
2    0.0000
3    0.0083
dtype: object

In [322]:
#How to format all the values in a dataframe as percentages?

df = pd.DataFrame(np.random.random(4), columns=['random'])
df
df.applymap(lambda x: str(round(x)**100) + '%')

out = df.style.format({'random':'{0:.2%}'.format})
out



random
0  0.047599
1  0.447058
2  0.870636
3  0.668819

random
0     0%
1     0%
2     1%
3     1%

In [323]:
#How to filter every nth row in a dataframe?
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

df.iloc[::20, :][['Manufacturer', 'Model', 'Type']]

Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small

In [324]:
#How to create a primary key index by combining relevant columns?
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv', usecols=[0,1,2,3,5])

df
df[['Manufacturer', 'Model', 'Type']] = df[['Manufacturer', 'Model', 'Type']].fillna('missing')
df.index = df.Manufacturer + '_' + df.Model + '_' + df.Type
df.index.is_unique

Manufacturer    Model     Type  Min.Price  Max.Price
0         Acura  Integra    Small       12.9       18.8
1           NaN   Legend  Midsize       29.2       38.7
2          Audi       90  Compact       25.9       32.3
3          Audi      100  Midsize        NaN       44.6
4           BMW     535i  Midsize        NaN        NaN
..          ...      ...      ...        ...        ...
88   Volkswagen  Eurovan      Van       16.6       22.7
89   Volkswagen   Passat  Compact       17.6       22.4
90   Volkswagen  Corrado   Sporty       22.9       23.7
91        Volvo      240  Compact       21.8       23.5
92          NaN      850  Midsize       24.8       28.5

[93 rows x 5 columns]

True

In [325]:
#How to get the row number of the nth largest value in a column?

df = pd.DataFrame(np.random.randint(1, 30, 30).reshape(10,-1), columns=list('abc'))
df
n=5
df['a'].argsort()[::-1][:4]


a   b   c
0   4  28  23
1   4  12   5
2  17  27  22
3   3  18  16
4  14   4   6
5  11  11  10
6  11  25  21
7  24  13  14
8   2  15   5
9  16  16  17

9    7
8    2
7    9
6    4
Name: a, dtype: int64

In [326]:
# How to find the position of the nth largest value greater than a given value?
ser = pd.Series(np.random.randint(1, 100, 15))
print('ser:' , ser.tolist(), 'mean', round(ser.mean()))

np.argwhere(ser > ser.mean())



ser: [78, 12, 43, 4, 4, 3, 56, 66, 94, 28, 2, 11, 97, 96, 36] mean 42


array([[ 0],
       [ 2],
       [ 6],
       [ 7],
       [ 8],
       [12],
       [13]], dtype=int64)

In [327]:
#How to get the last n rows of a dataframe with row sum > 100?

df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
rowsums = df.apply(np.sum, axis = 1)
last_row = df.iloc[np.where(rowsums > 100)][[0]][-2:]
last_row

0
11  14
14  11

In [328]:
#How to find and cap outliers from a series or dataframe column?
ser = pd.Series(np.logspace(-2, 2, 30))
ser.quantile([0.05,0.95])
print ('-------')
def cap_outliers(ser, low_perc, high_perc):
    low, high = ser.quantile([low_perc,high_perc])
    low,high
    ser[ser < low] = low
    ser[ser > high] = high
    return (ser)
capped_ser = cap_outliers(ser, 0.05, 0.95)
capped_ser


0.05     0.016049
0.95    63.876672
dtype: float64

-------


0      0.016049
1      0.016049
2      0.018874
3      0.025929
4      0.035622
        ...    
25    28.072162
26    38.566204
27    52.983169
28    63.876672
29    63.876672
Length: 30, dtype: float64

In [329]:
#How to reshape a dataframe to the largest possible square after removing the negative values?
df = pd.DataFrame(np.random.randint(-20, 50, 100).reshape(10,-1))
#step 1 remove negative values
arr = df[df>0].values.flatten()
arr_qualified  = arr[~np.isnan(arr)]
arr_qualified
#step 2 find n
n = int(np.floor(arr_qualified.shape[0]**0.5))
#step 3 take n value and reshape
top_indexes = np.argsort(arr_qualified)[::-1]
output = np.take(arr_qualified, sorted(top_indexes[:n**2])).reshape(n,-1)
output

array([ 47.,  38.,  30.,  29.,  48.,  48.,  32.,  21.,  48.,  31.,  30.,
        41.,  24.,  28.,  17.,  29.,  37.,   1.,  39.,  39.,  35.,   7.,
        37.,  44.,  24.,  46.,  22.,   9.,  35.,  22.,  48.,  13.,   2.,
        27.,   5.,   5.,  49.,   5.,  49.,  19.,  28.,  21.,  24.,  40.,
        49.,  35.,  48.,  42.,  11.,   3.,  24.,  11.,  37.,  32.,  12.,
        46.,   4.,   1.,  46.,  46.,   4.,  40.,   5.,  25.,  17.,  23.,
        17.])

array([[ 47.,  38.,  30.,  29.,  48.,  48.,  32.,  21.],
       [ 48.,  31.,  30.,  41.,  24.,  28.,  17.,  29.],
       [ 37.,  39.,  39.,  35.,   7.,  37.,  44.,  24.],
       [ 46.,  22.,   9.,  35.,  22.,  48.,  13.,  27.],
       [  5.,   5.,  49.,   5.,  49.,  19.,  28.,  21.],
       [ 24.,  40.,  49.,  35.,  48.,  42.,  11.,   3.],
       [ 24.,  11.,  37.,  32.,  12.,  46.,   4.,  46.],
       [ 46.,   4.,  40.,   5.,  25.,  17.,  23.,  17.]])

In [330]:
#How to swap two rows of a dataframe?
df = pd.DataFrame(np.arange(25).reshape(5, -1))
df
def swap_row(df, i1, i2):
    a, b = df.iloc[i1,:].copy(), df.iloc[i2,:].copy()
    df.iloc[i1,:], df.iloc[i2,:] = b, a 
    return df

oupt = swap_row(df, 3,4)
oupt

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  20  21  22  23  24
4  15  16  17  18  19

In [331]:
#Reverse all the rows of dataframe df.
df = pd.DataFrame(np.arange(25).reshape(5, -1))
df
df.iloc[::-1,:]

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

0   1   2   3   4
4  20  21  22  23  24
3  15  16  17  18  19
2  10  11  12  13  14
1   5   6   7   8   9
0   0   1   2   3   4

In [332]:
# How to create one-hot encodings of a categorical variable (dummy variables)?
df = pd.DataFrame(np.arange(25).reshape(5,-1), columns=list('abcde'))

df
df_onehot = pd.concat([pd.get_dummies(df['a']), df[list('bcde')]], axis= 1)
df_onehot

a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

0  5  10  15  20   b   c   d   e
0  1  0   0   0   0   1   2   3   4
1  0  1   0   0   0   6   7   8   9
2  0  0   1   0   0  11  12  13  14
3  0  0   0   1   0  16  17  18  19
4  0  0   0   0   1  21  22  23  24

In [333]:
#Which column contains the highest number of row-wise maximum values?
df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1))
df
df.apply(np.argmax, axis = 1).value_counts().index[0]


0   1   2   3
0  53  25  88  26
1  86  73  66  11
2  14  38  60  80
3  28  37  82  68
4  37  61  33  75
5  62  96  10  93
6  79  21  91  70
7  83  85  33  63
8  25  44  29  39
9   1  23  72  82

3

In [334]:
#How to create a new column that contains the row number of nearest column by euclidean distance?
df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1), columns=list('pqrs'), index=list('abcdefghij'))
df
nearest_rows = []
nearest_distance = []

#iterate rows
for i, row  in df.iterrows():
    curr = row
    rest = df.drop(i)
    e_dists  ={}
    for j, contestant in rest.iterrows():
        #计算Euclidean距离
        e_dists.update({j:round(np.linalg.norm(curr.values - contestant.values))})
    nearest_rows.append(max(e_dists, key=e_dists.get))
    nearest_distance.append(max(e_dists.values()))

df['nearest_row'] = nearest_rows
df['dist'] = nearest_distance
df

p   q   r   s
a   6  20  77  64
b  34  49  66  16
c  34  45   9  41
d  25  48  99  25
e  87  29  28   2
f  93  61  99  37
g  71  85  92  21
h  41  34  25  15
i  43  49   7  98
j  83  32  63  68

p   q   r   s nearest_row   dist
a   6  20  77  64           e  114.0
b  34  49  66  16           i  101.0
c  34  45   9  41           f  109.0
d  25  48  99  25           i  119.0
e  87  29  28   2           a  114.0
f  93  61  99  37           i  122.0
g  71  85  92  21           i  123.0
h  41  34  25  15           f   97.0
i  43  49   7  98           g  123.0
j  83  32  63  68           d   82.0

In [335]:
#How to know the maximum possible correlation value of each column against other columns?
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1), columns=list('pqrstuvwxy'), index=list('abcdefgh'))
df
abs_corrmat = np.abs(df.corr())

max_corr = abs_corrmat.apply(lambda x : sorted(x)[-2])
abs_corrmat
max_corr
np.round(max_corr.tolist(),2)

p   q   r   s   t   u   v   w   x   y
a  72  88   6  77  20  72  14   6  88  93
b  20   8  10  77  97   2  27  26  15  61
c  90  59  37  98  13  48  51  25  49  79
d  30  43  90  17  14  19  88  71  45  95
e  65  66  85   5  30  81  45  10   2  26
f  18  96  65  38  76  87  66  33  32  83
g  10  31  78  21   5  97  27   4  32  32
h  90  18  11  35  13  98   8  17  65  49

p         q         r         s         t         u         v  \
p  1.000000  0.114073  0.444360  0.331024  0.468664  0.217452  0.348531   
q  0.114073  1.000000  0.199809  0.046612  0.017395  0.334003  0.307847   
r  0.444360  0.199809  1.000000  0.739600  0.227799  0.115649  0.718805   
s  0.331024  0.046612  0.739600  1.000000  0.223545  0.382538  0.275448   
t  0.468664  0.017395  0.227799  0.223545  1.000000  0.412163  0.074096   
u  0.217452  0.334003  0.115649  0.382538  0.412163  1.000000  0.371555   
v  0.348531  0.307847  0.718805  0.275448  0.074096  0.371555  1.000000   
w  0.263878  0.061137  0.356996  0.142841  0.112648  0.605868  0.818036   
x  0.481115  0.211549  0.533198  0.400609  0.463545  0.191246  0.324367   
y  0.033874  0.415368  0.214613  0.480694  0.103987  0.435505  0.416507   

          w         x         y  
p  0.263878  0.481115  0.033874  
q  0.061137  0.211549  0.415368  
r  0.356996  0.533198  0.214613  
s  0.142841  0.400609  0.480694  
t  0.112648  0.463545  0.103987  
u  0.605868  0.191246  0.435505  
v  0.818036  0.324367  0.416507  
w  1.000000  0.054489  0.587110  
x  0.054489  1.000000  0.567295  
y  0.587110  0.567295  1.000000

p    0.481115
q    0.415368
r    0.739600
s    0.739600
t    0.468664
u    0.605868
v    0.818036
w    0.818036
x    0.567295
y    0.587110
dtype: float64

array([ 0.48,  0.42,  0.74,  0.74,  0.47,  0.61,  0.82,  0.82,  0.57,  0.59])

In [336]:
#How to create a column containing the minimum by maximum of each row?
df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1))
df
max_row = df.apply(lambda x :np.min(x)/np.max(x) ,axis=1)
max_row

0   1   2   3
0  35  32  69  53
1  27  93  92  67
2  72  50  61  31
3  42  57  24  20
4  87  67  40  25
5  37  57  18  37
6  75  38  60  64
7  87  50  98   5
8  74  56  83  76
9  12  97  50  97

0    0.463768
1    0.290323
2    0.430556
3    0.350877
4    0.287356
5    0.315789
6    0.506667
7    0.051020
8    0.674699
9    0.123711
dtype: float64

In [337]:
#How to create a column that contains the penultimate value in each row?
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))
df
row = df.apply(lambda x: sorted(x)[-2], axis= 1)
row

0   1   2   3   4   5   6   7   8   9
0  50  36  40  46  23  96  83  32  65  78
1  18  22  84  45   5  72   7  80  48  91
2  96  76   7  80  10  60  53  35  68  80
3  64  50  54  97  23  94  56  89  64  73
4   7  63  68  95  63  65  62   6  20  57
5  38  60  44  54  15  92  82  85  51  65
6  66  65  82  47  44   1  94  45  79  28
7  85  67  98  28   9  51  45  70  90  40

0    83
1    84
2    80
3    94
4    68
5    85
6    82
7    90
dtype: int64

In [338]:
#How to normalize all columns in a dataframe?
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))
df
out1 = df.apply(lambda x:((x - x.mean())/x.std()).round(2))
out1

0   1   2   3   4   5   6   7   8   9
0  25  25  32  49  20  62   6  37  22  47
1  54  93  48  68  62  95  97  59  99  81
2  32  13  69  14  84  26   6  36   9  99
3  19   8  98  62   7  45  92  80  36  64
4  15  51  20  11  24  99  37  15  87  63
5  81  84  24   9  16  80  71  77  11  86
6  97  14  21  80  57  36  38  57  54  61
7  85  61  35  31  21  14  28  40  68  83

0     1     2     3     4     5     6     7     8     9
0 -0.79 -0.56 -0.41  0.30 -0.60  0.15 -1.14 -0.59 -0.76 -1.53
1  0.09  1.47  0.17  0.98  0.93  1.18  1.40  0.40  1.48  0.47
2 -0.58 -0.91  0.93 -0.94  1.73 -0.97 -1.14 -0.64 -1.14  1.53
3 -0.98 -1.06  1.99  0.77 -1.07 -0.38  1.26  1.35 -0.36 -0.53
4 -1.10  0.22 -0.85 -1.05 -0.45  1.31 -0.28 -1.58  1.13 -0.59
5  0.91  1.21 -0.71 -1.12 -0.74  0.72  0.67  1.21 -1.08  0.77
6  1.40 -0.88 -0.81  1.41  0.75 -0.66 -0.25  0.31  0.17 -0.71
7  1.04  0.52 -0.30 -0.34 -0.56 -1.35 -0.53 -0.46  0.57  0.59

In [339]:
#How to compute the correlation of each row with the suceeding row?
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))
df
[df.iloc[i].corr(df.iloc[i+1]).round(2) for i in range(df.shape[0])[:-1]]

0   1   2   3   4   5   6   7   8   9
0   2  82  93  99  63  17  81  22  75  80
1  67  17  67  96   6   7  65  45  73  19
2  12  61  59  64  67  90  35  77  57  22
3  13  27  55  73  83  61  73  98  36  74
4  38  76  46  92  82  46   6  18  50  83
5  89  84  28  47  62  22  42  56  24  72
6  12  21  60  36  72  31  95  49  40  76
7   1  92   7  45  54  88  63  98  24   7

[0.27000000000000002,
 -0.26000000000000001,
 0.39000000000000001,
 -0.040000000000000001,
 0.26000000000000001,
 -0.23999999999999999,
 -0.080000000000000002]

In [340]:
#How to replace both the diagonals of dataframe with 0?
df = pd.DataFrame(np.random.randint(1,100, 100).reshape(10, -1))
df
for i in range(df.shape[0]):
    df.iloc[i,i] = 0
    df.iloc[df.shape[0] - i-1, i] = 0
    
df

0   1   2   3   4   5   6   7   8   9
0   2  10  77  42  90  83  46  88  46  68
1  66  14  43  82  83  41  80  88  85  41
2  91  74   1  43  18  49  15  97  63  91
3  89  21  91  75  67   9  31  19  84  93
4  40  78  97  90  32  51   5   9  90  55
5  72  73  76  72  72  54  85  61   9  12
6  44  39  58  42  96  34   1  86  83  95
7  58   3  48  94   6  62   3  67   1  64
8  45  42  30  39  44  46  83   7  79  20
9  76  22  80  39  64  26  88  64  30  71

0   1   2   3   4   5   6   7   8   9
0   0  10  77  42  90  83  46  88  46   0
1  66   0  43  82  83  41  80  88   0  41
2  91  74   0  43  18  49  15   0  63  91
3  89  21  91   0  67   9   0  19  84  93
4  40  78  97  90   0   0   5   9  90  55
5  72  73  76  72   0   0  85  61   9  12
6  44  39  58   0  96  34   0  86  83  95
7  58   3   0  94   6  62   3   0   1  64
8  45   0  30  39  44  46  83   7   0  20
9   0  22  80  39  64  26  88  64  30   0

In [341]:
#How to get the particular group of a groupby dataframe by key?
df = pd.DataFrame({'col1': ['apple', 'banana', 'orange'] * 3,
                   'col2': np.random.rand(9),
                   'col3': np.random.randint(0, 15, 9)})

df_grouped = df.groupby(['col1'])

df_grouped.get_group('apple')


col1      col2  col3
0  apple  0.866813     1
3  apple  0.472220    12
6  apple  0.235343     0

In [342]:
# How to get the n’th largest value of a column when grouped by another column?
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'rating': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})
df_grouped = df.groupby('fruit')['price']
df_grouped.get_group('banana').sort_values().iloc[-2]


11

In [343]:
#How to join two dataframes by 2 columns so they have only the common rows?
df1 = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                    'weight': ['high', 'medium', 'low'] * 3,
                    'price': np.random.randint(0, 15, 9)})

df2 = pd.DataFrame({'pazham': ['apple', 'orange', 'pine'] * 2,
                    'kilo': ['high', 'low'] * 3,
                    'price': np.random.randint(0, 15, 6)})

df = pd.merge(df1, df2, how='inner', left_on=['fruit', 'weight'], right_on=['pazham', 'kilo'], suffixes=['_left', '_right'])
df


fruit  price_left weight  kilo  pazham  price_right
0   apple           2   high  high   apple           11
1   apple           5   high  high   apple           11
2   apple           5   high  high   apple           11
3  orange           0    low   low  orange            8
4  orange           4    low   low  orange            8
5  orange           2    low   low  orange            8

In [344]:
#How to remove rows from a dataframe that are present in another dataframe?
df1 = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                    'weight': ['high', 'medium', 'low'] * 3,
                    'price': np.random.randint(0, 15, 9)})

df2 = pd.DataFrame({'pazham': ['apple', 'orange', 'pine'] * 2,
                    'kilo': ['high', 'low'] * 3,
                    'price': np.random.randint(0, 15, 6)})

df1[~df1.isin(df2).all(1)]


fruit  price  weight
0   apple     14    high
1  banana     12  medium
2  orange      1     low
3   apple     12    high
4  banana      6  medium
5  orange      4     low
6   apple      4    high
7  banana      9  medium
8  orange      0     low

In [345]:
#How to get the positions where values of two columns match?

df = pd.DataFrame({'fruit1': np.random.choice(['apple', 'orange', 'banana'], 10),
                    'fruit2': np.random.choice(['apple', 'orange', 'banana'], 10)})

df
np.where(df.fruit1 == df.fruit2)

fruit1  fruit2
0   apple   apple
1   apple  orange
2  orange  orange
3   apple  banana
4  orange   apple
5  banana  banana
6  banana  banana
7  orange   apple
8   apple   apple
9  banana  orange

(array([0, 2, 5, 6, 8], dtype=int64),)

In [346]:
#How to create lags and leads of a column in a dataframe?
df = pd.DataFrame(np.random.randint(1, 100, 20).reshape(-1, 4), columns = list('abcd'))
df
df['a_lag1'] = df['a'].shift(1)
df['b_lead1'] = df['b'].shift(-1)
df

a   b   c   d
0  12  26  80  44
1  96  52   6  11
2  11  71  60  77
3  74  79  79  46
4  65   1  45  80

a   b   c   d  a_lag1  b_lead1
0  12  26  80  44     NaN     52.0
1  96  52   6  11    12.0     71.0
2  11  71  60  77    96.0     79.0
3  74  79  79  46    11.0      1.0
4  65   1  45  80    74.0      NaN

In [347]:
#How to get the frequency of unique values in the entire dataframe?
df = pd.DataFrame(np.random.randint(1, 10, 20).reshape(-1, 4), columns = list('abcd'))
df
pd.value_counts(df.values.ravel())
#Return the flattened underlying data as an ndarray (ravel)

a  b  c  d
0  3  4  6  3
1  6  8  5  7
2  6  9  1  3
3  1  2  5  9
4  9  8  4  7

9    3
6    3
3    3
8    2
7    2
5    2
4    2
1    2
2    1
dtype: int64

In [348]:
#How to split a text column into two separate columns?
df = pd.DataFrame(["STD, City    State",
"33, Kolkata    West Bengal",
"44, Chennai    Tamil Nadu",
"40, Hyderabad    Telengana",
"80, Bangalore    Karnataka"], columns=['row'])
df
df_out = df.row.str.split(',|\t', expand=True)
df_out
new_header= df_out.iloc[0]
df_out = df_out[1:]
df_out.columns = new_header
df_out

row
0          STD, City    State
1  33, Kolkata    West Bengal
2   44, Chennai    Tamil Nadu
3  40, Hyderabad    Telengana
4  80, Bangalore    Karnataka

0                        1
0  STD            City    State
1   33   Kolkata    West Bengal
2   44    Chennai    Tamil Nadu
3   40   Hyderabad    Telengana
4   80   Bangalore    Karnataka

0 STD            City    State
1  33   Kolkata    West Bengal
2  44    Chennai    Tamil Nadu
3  40   Hyderabad    Telengana
4  80   Bangalore    Karnataka